AmiruthaVallii/climate-monitor

- .github/workflows/ci.yaml
- Github workflow to run pylint and pytest
- closes #6
> lint and test workflow

- db/schema.sql
- db/seed.sql
added locations to seed and some forgotten commas to schema
> 17 system component write schemasql to set up database schema

- extract-past/air_quality/dockerfile
- extract-past/weather/dockerfile
- extract-present-air-quality/dockerfile
- extract-present/dockerfile
- extract-present/extract.py
- Written docker files for:
- `extract-past/weather/extract.py`
- `extract-past/weather/extract_air_quality.py`
- `extract-present/extract.py`
- `extract-present-air-quality/extract.py`
- Tested all locally as outlined [here](https://docs.aws.amazon.com/lambda/latest/dg/python-image.html).
- Pushed to corresponding ECRs.
> 51 etl write dockerfiles for lambdas

- db/dockerfile
- db/event.json
- db/location_assignment_handler.py
- db/seed_flood_area_assignment.py
- extract-future/dockerfile
- extract-future/extract_future.py
dockerfile to run location assignment handler
dockerfile to run future climate data handler
> dockerfiles for future data and location assignment

- terraform/main.tf
- terraform/variables.tf
- Cloudwatch log group, lambda function Terraform config complete
- Added corresponding variable to `variables.tf`
> Terraform for live flood warnings lambda complete

- live-flood-monitoring-etl/fetch_live_flood_warnings.py
- Rebuilt docker image and pushed to ECR
> Changed except block so it doesn't return anything

- terraform/main.tf
When I tested the orchestrator Lambda on AWS, it was unable to run as it lacked the correct permission
I have created a new IAM role for the orchestrator Lambdas which will give them the correct permissions
@lindengraves you will need to assign your orchestrator Lambda to this role as well
> Created new Lambda IAM role

- extract-past/weather/extract.py
- extract-past/weather/test_extract.py
This will insert the data into the database in chunks of 5000 rows which should reduce the memory used, hopefully avoiding the RDS killing the connection.
I also added some logging.
I have already pushed this change to the ECR and updated the lambda to run this.
> Added chunksize=5000 to to_sql.

- orchestrator-new-location/dockerfile
- orchestrator-new-location/new_location_orchestrator.py
- orchestrator-new-location/requirements.txt
- Triggers `
c18-climate-monitor-historic-air-quality-lambda`, `c18-climate-monitor-future-predictions-lambda`, `
c18-climate-monitor-historic-weather-lambda`, `
c18-climate-monitor-location-assignment-lambda`
- Tested locally and it works
- Have pushed to ECR.
> 56 ETL Orchestrator lambda for historical/future data

- terraform/main.tf
Created an eventbridge scheduler to invoke the live readings orchestrator lambda every 15 minutes
> Created scheduler for live weather and air quality readings

- extract-past/weather/extract.py
Database was getting overloaded with connections.
> Added engine.dispose()

- .github/workflows/ci.yaml
- dashboard/.streamlit/config.toml
- dashboard/login.py
- dashboard/modules/nav.py
- dashboard/pages/air_quality.py
- dashboard/pages/floods.py
- dashboard/pages/profile.py
- dashboard/pages/weather.py
Nicely formatted sidebar that doesn't use file names as page titles.
> Format sidebar

- dashboard/login.py
- dashboard/modules/nav.py
- dashboard/pages/profile.py
> Redirects to profile page on login, redirect to login page on logout

- db/schema.sql
closes: #135 
- Added indexes on location_id to speed up querying.
- I have run these in the database
- Significant speedup when querying by location if in historical_weather_readings, (10s -> 1s)
> Added indexes

- dashboard/homepage.py
- dashboard/modules/nav.py
- dashboard/pages/air_quality.py
- dashboard/pages/floods.py
- dashboard/pages/login.py
- dashboard/pages/profile.py
- dashboard/pages/weather.py
- Created a homepage, which describes each page of the dashboard
- Added a line divider to each page
- Made all pages have the same location chooser in the sidebar
> Created homepage

- dashboard/pages/profile.py
- Added submit new location functionality
- Improved notification manager
closes: #134
> Profile page improvements

- terraform/main.tf
- terraform/variables.tf
- Added environment variables to github secrets
> Terraform config for dashboard done

- daily-summary/dockerfile
- daily-summary/requirements.txt
- daily-summary/summary.py
- Python code for daily summary lambda
- as well as dockerfile
- Tested locally and works
> 144 new feature daily summary email

- terraform/main.tf
- Notifications ECR repo is called `c18-climate-monitor-notifications-ecr`
> Terraform for notifications ECR done

- README.md
Briefly described project 
Instructions on how to setup page
Added file descriptions
> added readme with all files described

- terraform/main.tf
- terraform/variables.tf
- Provisions lambda to send users notifications
- Pulls image from `c18-climate-monitor-notifications-ecr`
> Terraform config for notifications lambda done
